# config/packages/security.yaml
security:
  # encodeurs de mot de passe / password hashers
  password_hashers:
    App\Entity\User:
      algorithm: auto

  # providers
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # firewalls
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      user_checker: App\Security\UserChecker

      form_login:
        login_path: app_login
        check_path: app_login
        default_target_path: client_home
        always_use_default_target_path: true

      logout:
        path: app_logout
        target: app_login
    # accès aux routes
  access_control:
    # Pages publiques
    - { path: ^/login$, roles: PUBLIC_ACCESS }
    - { path: ^/logout$, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }

    # Pages admin
    - { path: ^/user, roles: ROLE_ADMIN }
    - { path: ^/category, roles: ROLE_ADMIN }
    - { path: ^/business/photo, roles: ROLE_ADMIN }
    - { path: ^/review/photo, roles: ROLE_ADMIN }
    - { path: ^/admin/dashboard, roles: ROLE_ADMIN }

    # Notifications accessibles à tous les connectés
    - { path: ^/notifications, roles: IS_AUTHENTICATED_FULLY }

    # Messages - accessibles à tous les utilisateurs connectés
    - { path: ^/messages, roles: IS_AUTHENTICATED_FULLY }

    # Subscriptions - accessibles à tous les utilisateurs connectés
    - { path: ^/subscription, roles: IS_AUTHENTICATED_FULLY }

    # Pages owner
    - { path: ^/owner/businesses, roles: ROLE_SERVICE_OWNER }

    # Toutes les autres routes nécessitent une authentification
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

    - { path: ^/notifications/unread-count, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }